In [1]:
import pandas as pd

In [7]:
todo = pd.read_excel("../CodigosUnicosTerritoriales_2018_v03.xls")
todo.head()

,Código Región,Nombre Región,Código Provincia,Nombre Provincia,Código Comuna 2017,Nombre Comuna
0,1,Tarapacá,11,Iquique,1101,Iquique
1,1,Tarapacá,11,Iquique,1107,Alto Hospicio
2,1,Tarapacá,14,Tamarugal,1401,Pozo Almonte
3,1,Tarapacá,14,Tamarugal,1402,Camiña
4,1,Tarapacá,14,Tamarugal,1403,Colchane

In [23]:
regiones = todo[['Código Región','Nombre Región']]
regiones = regiones.drop_duplicates().set_index('Código Región')
regiones.head(20)

                                           Nombre Región
Código Región
1                                               Tarapacá
2                                            Antofagasta
3                                                Atacama
4                                               Coquimbo
5                                             Valparaíso
6                  Libertador General Bernardo O'Higgins
7                                                  Maule
8                                                 Biobío
9                                           La Araucanía
10                                             Los Lagos
11             Aysén del General Carlos Ibáñez del Campo
12                  Magallanes y de la Antártica Chilena
13                             Metropolitana de Santiago
14                                              Los Ríos
15                                    Arica y Parinacota
16                                                 Ñuble

In [24]:
provincias = todo[['Código Provincia','Nombre Provincia','Código Región']]
provincias = provincias.drop_duplicates().set_index('Código Provincia')
provincias.head(20)

                         Nombre Provincia  Código Región
Código Provincia
11                                Iquique              1
14                              Tamarugal              1
21                            Antofagasta              2
22                                 El Loa              2
23                              Tocopilla              2
31                                Copiapó              3
32                               Chañaral              3
33                                 Huasco              3
41                                  Elqui              4
42                                 Choapa              4
43                                 Limarí              4
51                             Valparaíso              5
52                         Isla de Pascua              5
53                              Los Andes              5
54                                Petorca              5
55                               Quillota              5
56                            San Antonio              5
57                San Felipe de Aconcagua              5
58                            Marga Marga              5
61                              Cachapoal              6

In [25]:
comunas = todo[['Código Comuna 2017','Nombre Comuna','Código Provincia']]
comunas = comunas.drop_duplicates()
comunas = comunas.set_index('Código Comuna 2017')
comunas.head(20)

                           Nombre Comuna  Código Provincia
Código Comuna 2017
1101                             Iquique                11
1107                       Alto Hospicio                11
1401                        Pozo Almonte                14
1402                              Camiña                14
1403                            Colchane                14
1404                               Huara                14
1405                                Pica                14
2101                         Antofagasta                21
2102                          Mejillones                21
2103                        Sierra Gorda                21
2104                              Taltal                21
2201                              Calama                22
2202                             Ollagüe                22
2203                San Pedro de Atacama                22
2301                           Tocopilla                23
2302                         María Elena                23
3101                             Copiapó                31
3102                             Caldera                31
3103                     Tierra Amarilla                31
3201                            Chañaral                32

In [20]:
len(comunas)

346

In [26]:
regiones.to_csv("Localidades/regiones.csv")
provincias.to_csv("Localidades/provincias.csv")
comunas.to_csv("Localidades/comunas.csv")