In [1]:
import pandas as pd
import time

In [2]:
coes_o = pd.read_csv("./COES/accionesdeprotesta_2012-2017_v.1.csv")
print(len(coes_o))
coes_o.head()

11511

/home/vicente/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (3,8,63,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,medio,pa,p0,p1,p2a,p2b,p2c,p3,p3a,p4,...,p28d,p28e,p28f,p29a,p29b,p29c,p29d,p29e,p29f,p29f_texto
0,EL MERCURIO,1,,2,10,11,17,C13,1,50,...,,,,30,,,,,,.
1,COMBINADOS,3,1,1,10,11,17,C13,1,50,...,,,,30,27,,,,,.
2,DIARIO LA REGIÓN DE COQUIMBO,0,,1,28,12,18,6,1,120,...,,,,2,,,,,,.
3,DIARIO DE ATACAMA,0,,1,13,1,18,4,1,56,...,,,,18,,,,,,.
4,AUSTRAL TEMUCO,0,,171,4,4,18,7,1,90,...,,,,1,19,,,,,.

In [3]:
#TABLA Acciones
variables_acciones = ['p2a','p2b','p2c','p3','p3a','p4',
                      'p1','p5a','p5b','p5c','p5d','p5e',
                      'p5f','p0','p8','p9','p9a','p10', 'p10a',
                      'p11','p11a','p12','p14a','p14b','p14c',
                      'p14d','p14e','p14f','p14g','p14h',
                      'p16','p21','p22a','p22b',
                      'p22c','p22d','p23','p24','p25',
                      'p26a','p26b','p26c','p26d','p26e',
                      'p26f','p27','p28a','p28b','p28c',
                      'p28d','p28e','p28f','medio']
columnas_acciones = ['fecha_observacion_d',
                     'fecha_observacion_m',
                     'fecha_observacion_a',
                     'numero_pagina ',
                     'tipo_noticia',
                     'numero_lineas',
                     'numero_respaldo',
                     'fecha_inicio_d',
                     'fecha_inicio_m',
                     'fecha_inicio_a',
                     'fecha_fin_d',
                     'fecha_fin_m',
                     'fecha_fin_a',
                     'repetida',
                     'comuna',
                     'localidad',
                     'rural_urbana',
                     'lugar_objetivo',
                     'id_episodio',
                     'numero_participantes',
                     'numero_participantes_episodio',
                     'numero_participantes_estimado',
                     'apunta_autoridad_nacional',
                     'apunta_autoridad_local',
                     'apunta_empresa',
                     'apunta_estado_extranjero',
                     'apunta_educativa',
                     'apunta_salud',
                     'apunta_actor_civil',
                     'apunta_otro',
                     'numero_organizaciones',
                     'presencia_carabineros',
                     'fuerza_cuerpo',
                     'fuerza_antidisturbios',
                     'fuerza_fuego',
                     'presencia_arrestos',
                     'numero_arrestos',
                     'numero_arrestos_estimado',
                     'presencia_heridos',
                     'manifestantes_heridos',
                     'manifestantes_heridos_estimado',
                     'seguridad_heridos',
                     'seguridad_heridos_estimado',
                     'terceros_heridos',
                     'terceros_heridos_estimado',
                     'presencia_muertos',
                     'manifestantes_muertos',
                     'manifestantes_muertos_estimado',
                     'seguridad_muertos',
                     'seguridad_muertos_estimado',
                     'terceros_muertos',
                     'terceros_muertos_estimado',
                     'id_medio']
acciones = coes_o[variables_acciones]
acciones.columns = columnas_acciones
acciones.head()

,fecha_observacion_d,fecha_observacion_m,fecha_observacion_a,numero_pagina,tipo_noticia,numero_lineas,numero_respaldo,fecha_inicio_d,fecha_inicio_m,fecha_inicio_a,...,terceros_heridos,terceros_heridos_estimado,presencia_muertos,manifestantes_muertos,manifestantes_muertos_estimado,seguridad_muertos,seguridad_muertos_estimado,terceros_muertos,terceros_muertos_estimado,id_medio
0,10,11,17,C13,1,50,2,1,1,12,...,,,2,,,,,,,EL MERCURIO
1,10,11,17,C13,1,50,1,1,1,12,...,,,2,,,,,,,COMBINADOS
2,28,12,18,6,1,120,1,2,1,12,...,,,2,,,,,,,DIARIO LA REGIÓN DE COQUIMBO
3,13,1,18,4,1,56,1,3,1,12,...,,,2,,,,,,,DIARIO DE ATACAMA
4,4,4,18,7,1,90,171,3,1,12,...,,,2,,,,,,,AUSTRAL TEMUCO

In [4]:
#Cast dates to datetime

#fecha_observacion
fecha_observacion = acciones[['fecha_observacion_d','fecha_observacion_m','fecha_observacion_a']]
fecha_observacion.columns = ['day','month','year']
print(fecha_observacion.iloc[0:10])
fecha_observacion.day = pd.to_numeric(fecha_observacion.day,errors='coerce')
fecha_observacion.month = pd.to_numeric(fecha_observacion.month,errors='coerce')
fecha_observacion.year = pd.to_numeric(fecha_observacion.year,errors='coerce')
fecha_observacion.year = fecha_observacion.year + 2000
fecha_observacion = pd.to_datetime(fecha_observacion,errors='coerce')
print(fecha_observacion.iloc[0:10])

#fecha_inicio
fecha_inicio = acciones[['fecha_inicio_d','fecha_inicio_m','fecha_inicio_a']]
fecha_inicio.columns = ['day','month','year']
fecha_inicio.day = pd.to_numeric(fecha_inicio.day,errors='coerce')
fecha_inicio.month = pd.to_numeric(fecha_inicio.month,errors='coerce')
fecha_inicio.year = pd.to_numeric(fecha_inicio.year,errors='coerce')
fecha_inicio.year = fecha_inicio.year + 2000
fecha_inicio = pd.to_datetime(fecha_inicio,errors='coerce')

#fecha_fin
fecha_fin = acciones[['fecha_fin_d','fecha_fin_m','fecha_fin_a']]
fecha_fin.columns = ['day','month','year']
fecha_fin.day = pd.to_numeric(fecha_fin.day,errors='coerce')
fecha_fin.month = pd.to_numeric(fecha_fin.month,errors='coerce')
fecha_fin.year = pd.to_numeric(fecha_fin.year,errors='coerce')
fecha_fin = fecha_fin.dropna().astype(int)
fecha_fin.year = fecha_fin.year + 2000
fecha_fin = pd.to_datetime(fecha_fin,errors='coerce')
fecha_fin.head()

  day month year
0  10    11   17
1  10    11   17
2  28    12   18
3  13     1   18
4   4     4   18
5  20    12   17
6  24    11   17
7  24    11   17
8   2    11   17
9  20    11   17
0   2017-11-10
1   2017-11-10
2   2018-12-28
3   2018-01-13
4   2018-04-04
5   2017-12-20
6   2017-11-24
7   2017-11-24
8   2017-11-02
9   2017-11-20
dtype: datetime64[ns]

/home/vicente/.local/lib/python3.6/site-packages/pandas/core/generic.py:4405: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

4    2012-01-03
18   2012-01-12
22   2012-01-14
23   2012-01-14
32   2012-01-22
dtype: datetime64[ns]

In [5]:
acciones = acciones.drop(['fecha_observacion_d','fecha_observacion_m','fecha_observacion_a',
                          'fecha_inicio_d','fecha_inicio_m','fecha_inicio_a',
                          'fecha_fin_d','fecha_fin_m','fecha_fin_a'],axis=1)

acciones = pd.concat([acciones,fecha_observacion,fecha_inicio,fecha_fin],axis=1)
acciones = acciones.rename(columns={0:'fecha_observacion',1:'fecha_inicio',2:'fecha_fin'})
acciones.head()

,numero_pagina,tipo_noticia,numero_lineas,numero_respaldo,repetida,comuna,localidad,rural_urbana,lugar_objetivo,id_episodio,...,manifestantes_muertos,manifestantes_muertos_estimado,seguridad_muertos,seguridad_muertos_estimado,terceros_muertos,terceros_muertos_estimado,id_medio,fecha_observacion,fecha_inicio,fecha_fin
0,C13,1,50,2,,8203,PAICAVI,0,.,,...,,,,,,,EL MERCURIO,2017-11-10,2012-01-01,NaT
1,C13,1,50,1,1,9101,BOYECO,0,.,,...,,,,,,,COMBINADOS,2017-11-10,2012-01-01,NaT
2,6,1,120,1,,4204,VALLE CHOAPA,0,.,,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2018-12-28,2012-01-02,NaT
3,4,1,56,1,,3202,INSTALACIONES DE TRANSPORTE Y CHANCADO DIVISIO...,0,.,,...,,,,,,,DIARIO DE ATACAMA,2018-01-13,2012-01-03,NaT
4,7,1,90,171,,9101,PLAZA TEODORO SCHMIDT,1,.,,...,,,,,,,AUSTRAL TEMUCO,2018-04-04,2012-01-03,2012-01-03

In [6]:
print(acciones.columns)

Index(['numero_pagina ', 'tipo_noticia', 'numero_lineas', 'numero_respaldo',
       'repetida', 'comuna', 'localidad', 'rural_urbana', 'lugar_objetivo',
       'id_episodio', 'numero_participantes', 'numero_participantes_episodio',
       'numero_participantes_estimado', 'apunta_autoridad_nacional',
       'apunta_autoridad_local', 'apunta_empresa', 'apunta_estado_extranjero',
       'apunta_educativa', 'apunta_salud', 'apunta_actor_civil', 'apunta_otro',
       'numero_organizaciones', 'presencia_carabineros', 'fuerza_cuerpo',
       'fuerza_antidisturbios', 'fuerza_fuego', 'presencia_arrestos',
       'numero_arrestos', 'numero_arrestos_estimado', 'presencia_heridos',
       'manifestantes_heridos', 'manifestantes_heridos_estimado',
       'seguridad_heridos', 'seguridad_heridos_estimado', 'terceros_heridos',
       'terceros_heridos_estimado', 'presencia_muertos',
       'manifestantes_muertos', 'manifestantes_muertos_estimado',
       'seguridad_muertos', 'seguridad_muertos_estimado', 'terceros_muertos',
       'terceros_muertos_estimado', 'id_medio', 'fecha_observacion',
       'fecha_inicio', 'fecha_fin'],
      dtype='object')

In [7]:
print(acciones[acciones.comuna.isnull()])

Empty DataFrame
Columns: [numero_pagina , tipo_noticia, numero_lineas, numero_respaldo, repetida, comuna, localidad, rural_urbana, lugar_objetivo, id_episodio, numero_participantes, numero_participantes_episodio, numero_participantes_estimado, apunta_autoridad_nacional, apunta_autoridad_local, apunta_empresa, apunta_estado_extranjero, apunta_educativa, apunta_salud, apunta_actor_civil, apunta_otro, numero_organizaciones, presencia_carabineros, fuerza_cuerpo, fuerza_antidisturbios, fuerza_fuego, presencia_arrestos, numero_arrestos, numero_arrestos_estimado, presencia_heridos, manifestantes_heridos, manifestantes_heridos_estimado, seguridad_heridos, seguridad_heridos_estimado, terceros_heridos, terceros_heridos_estimado, presencia_muertos, manifestantes_muertos, manifestantes_muertos_estimado, seguridad_muertos, seguridad_muertos_estimado, terceros_muertos, terceros_muertos_estimado, id_medio, fecha_observacion, fecha_inicio, fecha_fin]
Index: []

[0 rows x 47 columns]

In [8]:
#cambiar orden
#cambiar puntos por null
#Make boolean values 0 or 1

null_dict = {'.':'',' ':''}
ttz = {'2':'0'}

acciones = acciones.replace(null_dict)
acciones.apunta_actor_civil = acciones.apunta_actor_civil.astype(str).replace(ttz)
acciones.apunta_autoridad_local = acciones.apunta_autoridad_local.astype(str).replace(ttz)
acciones.apunta_empresa = acciones.apunta_empresa.astype(str).replace(ttz)
acciones.apunta_autoridad_nacional = acciones.apunta_autoridad_nacional.astype(str).replace(ttz)
acciones.apunta_educativa = acciones.apunta_educativa.astype(str).replace(ttz)
acciones.apunta_estado_extranjero = acciones.apunta_estado_extranjero.astype(str).replace(ttz)
acciones.apunta_otro = acciones.apunta_otro.astype(str).replace(ttz)
acciones.apunta_salud = acciones.apunta_salud.astype(str).replace(ttz)

acciones.presencia_carabineros = acciones.presencia_carabineros.astype(str).replace(ttz)
acciones.fuerza_cuerpo = acciones.fuerza_cuerpo.astype(str).replace(ttz)
acciones.fuerza_fuego = acciones.fuerza_fuego.astype(str).replace(ttz)
acciones.fuerza_antidisturbios = acciones.fuerza_antidisturbios.astype(str).replace(ttz)
acciones.presencia_arrestos = acciones.presencia_arrestos.astype(str).replace(ttz)
acciones.presencia_heridos = acciones.presencia_heridos.astype(str).replace(ttz)
acciones.presencia_muertos = acciones.presencia_muertos.astype(str).replace(ttz)

acciones.loc[acciones.localidad=='']

,numero_pagina,tipo_noticia,numero_lineas,numero_respaldo,repetida,comuna,localidad,rural_urbana,lugar_objetivo,id_episodio,...,manifestantes_muertos,manifestantes_muertos_estimado,seguridad_muertos,seguridad_muertos_estimado,terceros_muertos,terceros_muertos_estimado,id_medio,fecha_observacion,fecha_inicio,fecha_fin
23,22,1,41,6,,13101,,1,REGIONAL,,...,,,,,,,DIARIO LA PRENSA DE CURICÓ,2017-12-28,2012-01-14,2012-01-14
36,7,1,57,3,,1101,,1,,,...,,,,,,,LA ESTRELLA DE IQUIQUE,2018-01-10,2012-01-20,NaT
42,16,1,15,7,,13114,,1,,,...,,,,,,,LA ESTRELLA DE VALPARAÍSO,2018-01-08,2012-01-24,2012-01-31
68,2,1,278,3,,3101,,1,,,...,,,,,,,DIARIO DE ATACAMA,2018-01-13,2012-02-13,2012-02-13
114,2,1,184,7,,11201,,1,,,...,,,,,,,LA TERCERA,2018-01-29,2012-02-17,NaT
137,2,1,55,9,,11201,,1,,,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2018-12-28,2012-02-20,NaT
165,2,1,67,12,,11101,,1,,6114,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2018-12-28,2012-02-23,NaT
170,2,1,161,18,,11201,,1,,,...,,,,,,,LA TERCERA,2018-01-29,2012-02-24,NaT
188,6,1,74,14,,3101,,1,SECTOR DE LOS CARRERA CON DIEGO DE ALMAGRO,,...,,,,,,,DIARIO DE ATACAMA,2018-01-13,2012-02-28,NaT
219,10,1,74,26,,13123,,1,,6120,...,,,,,,,LA TERCERA,2018-01-29,2012-03-05,NaT
222,10,1,125,20,,11201,,,,,...,,,,,,,AUSTRAL VALDIVIA,2017-12-26,2012-03-06,NaT
259,3,1,68,28,,11201,,1,,,...,,,,,,,LA TERCERA,2018-01-29,2012-03-12,NaT
267,3,1,36,17,,4101,,1,,,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2018-12-28,2012-03-15,NaT
282,1,2,30,14,,13101,,1,GRAN SANTIAGO,,...,,,,,,,COOPERATIVA,2018-01-19,2012-03-15,2012-03-15
286,10,1,58,17,,13123,,1,,2501,...,,,,,,,LA ESTRELLA DE ANTOFAGASTA,2017-11-03,2012-03-15,NaT
289,17,1,24,18,,4102,,1,,,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2018-12-28,2012-03-16,NaT
305,5,1,81,8,,1101,,1,,,...,,,,,,,LA ESTRELLA DE IQUIQUE,2018-01-10,2012-03-20,2012-05-11
327,12,1,143,37,,3101,,1,,,...,,,,,,,LA TERCERA,2018-01-29,2012-03-22,NaT
344,C12,1,100,73,,8101,,1,,1008,...,,,,,,,EL MERCURIO,2017-11-24,2012-03-28,NaT
347,C12,1,100,73,,13122,,1,,1008,...,,,,,,,EL MERCURIO,2017-11-24,2012-03-28,NaT
354,10,1,147,42,,5101,,1,,1009,...,,,,,,,LA TERCERA,2018-01-29,2012-03-29,NaT
369,1,1,26,4,,6301,,1,,,...,,,,,,,BIO BIO,2017-11-27,2012-03-30,NaT
378,3,1,38,15,,1401,,1,,,...,,,,,,,LA ESTRELLA DE IQUIQUE,2018-01-10,2012-04-02,NaT
385,1,1,12,17,,13119,,1,,2503,...,,,,,,,DIARIO FINANCIERO,2017-12-04,2012-04-04,2012-04-04
387,1,1,12,18,,13124,,1,,2503,...,,,,,,,DIARIO FINANCIERO,2017-12-04,2012-04-04,2012-04-04
397,6,1,80,12,,7201,,1,,,...,,,,,,,DIARIO LA PRENSA DE CURICÓ,2017-12-28,2012-04-12,NaT
405,6,1,41,16,,1101,,1,,6070,...,,,,,,,LA ESTRELLA DE IQUIQUE,2018-01-10,2012-04-17,NaT
427,3,1,80,38,,3101,,,REGIONAL,,...,,,,,,,DIARIO DE ATACAMA,2018-01-14,2012-04-23,NaT
429,11,1,65,20,,1101,,1,,,...,,,,,,,LA ESTRELLA DE IQUIQUE,2018-01-10,2012-04-24,NaT
439,5,1,46,62,,1101,,1,,6124,...,,,,,,,LA TERCERA,2018-01-29,2012-04-25,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10953,6,1,59,107,,3301,,1,NACIONAL,104,...,,,,,,,DIARIO DE ATACAMA,2017-09-06,2017-08-31,2017-09-01
10980,1,2,14,525,,10301,,1,NACIONAL,6232,...,,,,,,,BIO BIO,2017-12-12,2017-09-03,NaT
10987,1,2,16,538,,10101,,1,,,...,,,,,,,BIO BIO,2017-12-12,2017-09-04,NaT
10992,3,1,74,46,,1101,,1,UNAP,,...,,,,,,,LA ESTRELLA DE IQUIQUE,2017-09-08,2017-09-05,2017-09-11
10993,12,1,26,115,,1101,,1,INTENDENCIA,,...,,,,,,,DIARIO DE ATACAMA,2017-10-07,2017-09-05,NaT
10994,3,1,30,50,342,5101,,1,NACIONAL,2044,...,,,,,,,COMBINADOS,2017-09-11,2017-09-05,NaT
11038,1,2,35,162,359,13101,,,NACIONAL,,...,,,,,,,COMBINADOS,2017-10-06,2017-09-11,2017-10-03
11039,C7,1,90,176,352,13106,,1,,3609,...,,,,,,,COMBINADOS,2017-09-27,2017-09-11,NaT
11048,1,2,49,168,355,13122,,1,,3609,...,,,,,,,COMBINADOS,2017-10-06,2017-09-11,NaT
11051,C7,1,90,177,357,13401,,1,,3609,...,,,,,,,COMBINADOS,2017-09-27,2017-09-11,NaT
11063,1,2,20,542,,9101,,1,,,...,,,,,,,BIO BIO,2017-12-18,2017-09-13,NaT
11088,1,1,23,8,,8101,,,NACIONAL,,...,,,,,,,DIARIO FINANCIERO,2017-01-10,2017-09-21,NaT
11121,1,2,13,535,,5101,,1,,,...,,,,,,,BIO BIO,2017-12-12,2017-09-26,2017-10-03
11182,3,1,126,33,,13101,,1,,,...,,,,,,,DIARIO LA PRENSA DE CURICÓ,2017-10-09,2017-10-02,NaT
11184,6,1,48,122,,3101,,1,,,...,,,,,,,DIARIO DE ATACAMA,2017-10-07,2017-10-03,NaT
11202,6,1,34,124,,3101,,1,,,...,,,,,,,DIARIO DE ATACAMA,2017-10-07,2017-10-07,NaT
11269,9,1,58,65,,4101,,1,,,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2017-12-27,2017-10-23,NaT
11281,6,1,50,57,,2101,,1,,,...,,,,,,,LA ESTRELLA DE ANTOFAGASTA,2017-12-12,2017-10-26,NaT
11315,,1,82,35,,7301,,1,,,...,,,,,,,DIARIO LA PRENSA DE CURICÓ,2017-12-27,2017-11-06,NaT
11348,1,2,27,658,,9101,,1,,,...,,,,,,,BIO BIO,2018-01-24,2017-11-11,NaT
11350,4,1,61,36,,7301,,1,,,...,,,,,,,DIARIO LA PRENSA DE CURICÓ,2017-12-27,2017-11-13,2017-11-15
11356,15,1,93,67,,4102,,1,,6212,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2017-12-27,2017-11-14,2017-11-15
11362,1,2,45,200,,13117,,1,NACIONAL,6212,...,,,,,,,LA TERCERA,2018-01-02,2017-11-14,NaT
11414,3,1,22,70,454,13101,,1,,,...,,,,,,,COMBINADOS,2017-12-27,2017-11-25,NaT
11415,4,1,179,134,,3101,,1,,,...,,,,,,,DIARIO DE ATACAMA,2017-12-23,2017-11-27,NaT
11423,15,1,192,71,,4102,,1,,,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2018-01-03,2017-11-29,NaT
11436,1,2,19,702,,5804,,1,,,...,,,,,,,BIO BIO,2018-01-24,2017-12-03,NaT
11438,5,1,22,138,,3301,,1,,,...,,,,,,,DIARIO DE ATACAMA,2018-01-03,2017-12-05,NaT
11441,15,1,210,72,,4102,,1,,,...,,,,,,,DIARIO LA REGIÓN DE COQUIMBO,2018-01-03,2017-12-06,NaT
11448,3,1,84,135,,3101,,1,,,...,,,,,,,DIARIO DE ATACAMA,2018-01-03,2017-12-07,NaT

In [9]:
print(acciones[acciones.fuerza_antidisturbios==2])

Empty DataFrame
Columns: [numero_pagina , tipo_noticia, numero_lineas, numero_respaldo, repetida, comuna, localidad, rural_urbana, lugar_objetivo, id_episodio, numero_participantes, numero_participantes_episodio, numero_participantes_estimado, apunta_autoridad_nacional, apunta_autoridad_local, apunta_empresa, apunta_estado_extranjero, apunta_educativa, apunta_salud, apunta_actor_civil, apunta_otro, numero_organizaciones, presencia_carabineros, fuerza_cuerpo, fuerza_antidisturbios, fuerza_fuego, presencia_arrestos, numero_arrestos, numero_arrestos_estimado, presencia_heridos, manifestantes_heridos, manifestantes_heridos_estimado, seguridad_heridos, seguridad_heridos_estimado, terceros_heridos, terceros_heridos_estimado, presencia_muertos, manifestantes_muertos, manifestantes_muertos_estimado, seguridad_muertos, seguridad_muertos_estimado, terceros_muertos, terceros_muertos_estimado, id_medio, fecha_observacion, fecha_inicio, fecha_fin]
Index: []

[0 rows x 47 columns]

In [10]:
#medios para claves
medios = coes_o['medio']
print(len(medios))
medios = medios.drop_duplicates()
medios = medios.reset_index(drop=True)
medios.columns = ['id_medio','nombre']
medios.head()

11511

0                     EL MERCURIO
1                      COMBINADOS
2    DIARIO LA REGIÓN DE COQUIMBO
3               DIARIO DE ATACAMA
4                  AUSTRAL TEMUCO
Name: medio, dtype: object

In [11]:
dmedios = medios.to_dict()
dmediosi = dict((val,key) for (key,val) in dmedios.items())
print(dmediosi)
acciones.id_medio.replace(dmediosi,inplace=True)
acciones.head()

{'EL MERCURIO': 0, 'COMBINADOS': 1, 'DIARIO LA REGIÓN DE COQUIMBO': 2, 'DIARIO DE ATACAMA': 3, 'AUSTRAL TEMUCO': 4, 'EL LLANQUIHUE': 5, 'LA ESTRELLA DE ARICA': 6, 'EL RANCAGÜINO - DIARIO VI REGIÓN': 7, 'LA ESTRELLA DE IQUIQUE': 8, 'LA ESTRELLA DE VALPARAÍSO': 9, 'DIARIO LA PRENSA DE CURICÓ': 10, 'LA PRENSA AUSTRAL': 11, 'DIARIO DE AYSÉN': 12, 'BIO BIO': 13, 'LA TERCERA': 14, 'LA ESTRELLA DE ANTOFAGASTA': 15, 'COOPERATIVA': 16, 'AUSTRAL VALDIVIA': 17, 'DIARIO FINANCIERO': 18}

,numero_pagina,tipo_noticia,numero_lineas,numero_respaldo,repetida,comuna,localidad,rural_urbana,lugar_objetivo,id_episodio,...,manifestantes_muertos,manifestantes_muertos_estimado,seguridad_muertos,seguridad_muertos_estimado,terceros_muertos,terceros_muertos_estimado,id_medio,fecha_observacion,fecha_inicio,fecha_fin
0,C13,1,50,2,,8203,PAICAVI,0,,,...,,,,,,,0,2017-11-10,2012-01-01,NaT
1,C13,1,50,1,1,9101,BOYECO,0,,,...,,,,,,,1,2017-11-10,2012-01-01,NaT
2,6,1,120,1,,4204,VALLE CHOAPA,0,,,...,,,,,,,2,2018-12-28,2012-01-02,NaT
3,4,1,56,1,,3202,INSTALACIONES DE TRANSPORTE Y CHANCADO DIVISIO...,0,,,...,,,,,,,3,2018-01-13,2012-01-03,NaT
4,7,1,90,171,,9101,PLAZA TEODORO SCHMIDT,1,,,...,,,,,,,4,2018-04-04,2012-01-03,2012-01-03

In [12]:
#TABLA medios
medios = coes_o[['medio','pa']]
medios = medios.drop_duplicates()
medios = medios.reset_index(drop=True)
medios.columns = ['nombre','tipo']
medios.head()

                         nombre  tipo
0                   EL MERCURIO     1
1                    COMBINADOS     3
2  DIARIO LA REGIÓN DE COQUIMBO     0
3             DIARIO DE ATACAMA     0
4                AUSTRAL TEMUCO     0

In [13]:
#TABLA tipo de medio
tmedio_d = {'id':[0,1,2,3],'nombre':['Circulación regional','Circulación nacional','Radio Biobío','Combinado']}
tipo_medio = pd.DataFrame(data=tmedio_d)
print(tipo_medio)

   id                nombre
0   0  Circulación regional
1   1  Circulación nacional
2   2          Radio Biobío
3   3             Combinado

In [14]:
#TABLA tipo de grupo social. Del anexo.
dict_tipos_gs = {'nombre':['Sexo/Edad','Grupos étnicos','Estudiantes','Grupos laborales','Partidos, religión y deporte','Consumidores y deudores','Grupos según vivenda/geografía','Grupos de género, ecologistas-animalistas, artistas','Clandestinos, presos, grupos de odio','Otros']}
tipos_grupo_social = pd.DataFrame(data=dict_tipos_gs)
tipos_grupo_social['id'] = tipos_grupo_social.index
tipos_grupo_social = tipos_grupo_social[['id','nombre']]
print(tipos_grupo_social)

   id                                             nombre
0   0                                          Sexo/Edad
1   1                                     Grupos étnicos
2   2                                        Estudiantes
3   3                                   Grupos laborales
4   4                       Partidos, religión y deporte
5   5                            Consumidores y deudores
6   6                     Grupos según vivenda/geografía
7   7  Grupos de género, ecologistas-animalistas, art...
8   8               Clandestinos, presos, grupos de odio
9   9                                              Otros

In [15]:
#TABLA grupo social. Del anexo.
dict_grupos_sociales = {'nombre':['Hombres','Mujeres','Jóvenes','Adultos mayores','Pueblos originarios: mapuche','Pueblos originarios: no mapuche','Pueblos originarios: Indeterminado','Inmigrantes','Estudiantes universitarios','Estudiantes secundarios','Estudiantes (indeterminado)','Trabajadores empleados en el sector público','Trabajadores empleados en el sector privado','Trabajadores por cuenta propia o de pymes','Trabajadores indeterminados','Desempleados, cesantes','Jubilados, pensionistas','Jefas de hogar','Grupos de simpatizantes o afiliados a partidos u organizaciones políticas','Grupos religiosos','Grupos relacionados a instituciones deportivas','Consumidores de vienes y servicios varios','Deudores','Personas sin hogar','Pobladores','Residentes o vecinos de un barrio, localidad, comuna o región','Homosexuales/minorías sexuales/feministas','Ecologistas/ambientalistas/animalistas','Artistas, comunicadores,periodistas','"Encapuchados", o cualquier grupo que intencionalmente oculte su identidad','Grupos de "odio"','Presos, detenidos','Familiares de presos o detenidos','Anarquistas, okupas, grupos libertarios'],
                        'tipo':[0,0,0,0,1,1,1,1,2,2,2,3,3,3,3,3,3,3,4,4,4,5,5,6,6,6,7,7,7,8,8,8,8,8]}
grupos_sociales = pd.DataFrame(data = dict_grupos_sociales)
#agregar otros
otros_grupos_sociales = coes_o[['p13d_texto']]
otros_grupos_sociales.drop_duplicates(inplace=True)
otros_grupos_sociales = otros_grupos_sociales.drop([0])
otros_grupos_sociales = otros_grupos_sociales.reset_index(drop=True)
otros_grupos_sociales.index = otros_grupos_sociales.index + 34
otros_grupos_sociales['tipo'] = 9
otros_grupos_sociales.rename(columns={'p13d_texto':'nombre'},inplace=True)
grupos_sociales = grupos_sociales.append(otros_grupos_sociales)
grupos_sociales['id'] = grupos_sociales.index  + 1
grupos_sociales = grupos_sociales[['id','nombre','tipo']]
print(grupos_sociales)

    id                                             nombre  tipo
0    1                                            Hombres     0
1    2                                            Mujeres     0
2    3                                            Jóvenes     0
3    4                                    Adultos mayores     0
4    5                       Pueblos originarios: mapuche     1
5    6                    Pueblos originarios: no mapuche     1
6    7                 Pueblos originarios: Indeterminado     1
7    8                                        Inmigrantes     1
8    9                         Estudiantes universitarios     2
9   10                            Estudiantes secundarios     2
10  11                        Estudiantes (indeterminado)     2
11  12        Trabajadores empleados en el sector público     3
12  13        Trabajadores empleados en el sector privado     3
13  14          Trabajadores por cuenta propia o de pymes     3
14  15                        Trabajadores indeterminados     3
15  16                             Desempleados, cesantes     3
16  17                            Jubilados, pensionistas     3
17  18                                     Jefas de hogar     3
18  19  Grupos de simpatizantes o afiliados a partidos...     4
19  20                                  Grupos religiosos     4
20  21     Grupos relacionados a instituciones deportivas     4
21  22          Consumidores de vienes y servicios varios     5
22  23                                           Deudores     5
23  24                                 Personas sin hogar     6
24  25                                         Pobladores     6
25  26  Residentes o vecinos de un barrio, localidad, ...     6
26  27          Homosexuales/minorías sexuales/feministas     7
27  28             Ecologistas/ambientalistas/animalistas     7
28  29                Artistas, comunicadores,periodistas     7
29  30  "Encapuchados", o cualquier grupo que intencio...     8
30  31                                   Grupos de "odio"     8
31  32                                  Presos, detenidos     8
32  33                   Familiares de presos o detenidos     8
33  34            Anarquistas, okupas, grupos libertarios     8
34  35                                         FAMILIARES     9
35  36                                         APODERADOS     9
36  37                                              NIÑOS     9
37  38                                       EX MILITARES     9
38  39                                        EMPRESARIOS     9
39  40                                           ENFERMOS     9
40  41                                     EX CONSCRIPTOS     9
41  42                                     DISCAPACITADOS     9
42  43                                EX PRESOS POLÍTICOS     9
43  44                                           BOMBEROS     9

/home/vicente/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [16]:
#TABLA grupo social de accion
#esto se podría hacer de forma más pythónica(?)
#base
grupo_social_aux = coes_o[['p13a','p13b','p13c','p13d']].values.flatten()
gs = pd.concat([pd.DataFrame([[i//4,v]],columns=['id_accion','id_grupo_social']) for i, v in enumerate(grupo_social_aux)],ignore_index=True)
gs.head()

   id_accion id_grupo_social
0          0              30
1          0
2          0
3          0
4          1              30

In [17]:
gs_nd = gs.drop_duplicates().reset_index(drop=True)
print(len(gs_nd))
gs_nd = gs_nd.drop(gs_nd[gs_nd.id_grupo_social==' '].index)
print(len(gs_nd))
print(gs_nd.head())

26649
15716
   id_accion id_grupo_social
0          0              30
2          1              30
3          1               5
5          2              26
7          3              13

In [18]:
#otros
otros_grupos_sociales.head()
ogs_aux = otros_grupos_sociales.drop(['tipo'],axis=1).to_dict()
ogs_aux = ogs_aux['nombre']
ogs_aux_i = dict((val,key) for (key,val) in ogs_aux.items())
print(ogs_aux_i)
ogs_rep = coes_o[['p13d_texto']].p13d_texto.replace(ogs_aux_i)
ogs_rep = ogs_rep.drop(ogs_rep[ogs_rep=='.'].index)
ogs_rep = pd.DataFrame(ogs_rep)
ogs_rep['id_accion'] = ogs_rep.index
ogs_rep.columns = ['id_grupo_social','id_accion']
ogs_rep.head()
grupos_accion = gs_nd.append(ogs_rep).astype('int').sort_values('id_accion')
grupos_accion = grupos_accion.drop(grupos_accion[grupos_accion.id_grupo_social==99].index)
grupos_accion = grupos_accion.reset_index(drop=True)
print(len(grupos_accion))
grupos_accion.iloc[335:400]

{'FAMILIARES': 34, 'APODERADOS': 35, 'NIÑOS': 36, 'EX MILITARES': 37, 'EMPRESARIOS': 38, 'ENFERMOS': 39, 'EX CONSCRIPTOS': 40, 'DISCAPACITADOS': 41, 'EX PRESOS POLÍTICOS': 42, 'BOMBEROS': 43}
15705

/home/vicente/.local/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

     id_accion  id_grupo_social
335        265               10
336        266               10
337        267               19
338        267               12
339        267               10
340        268                9
341        268               10
342        268               12
343        268               35
344        269               30
345        270               10
346        270                9
347        271               10
348        271                9
349        272               26
350        273               26
351        273                9
352        273               14
353        274               26
354        275               26
355        276               26
356        276               30
357        277               10
358        277                9
359        278               26
360        279                9
361        279               10
362        280               10
363        281                9
364        281               10
..         ...              ...
370        286               10
371        287                9
372        287               10
373        288               10
374        288                9
375        289               21
376        290               29
377        290               26
378        291               12
379        292               26
380        293               26
381        294               30
382        295               26
383        295               14
384        296                9
385        296               26
386        297               26
387        297               14
388        298               14
389        299               14
390        299               26
391        300               13
392        301                1
393        301                2
394        302               14
395        303               26
396        305               13
397        306               13
398        307               26
399        307               12

[65 rows x 2 columns]

In [19]:
#TABLA organizaciones
organizaciones_aux = coes_o[['p17a','p17b','p17c','p17d','p17e','p17f']].values.flatten()
orgs = pd.concat([pd.DataFrame([[i//6,v]],columns=['id_accion','organizacion']) for i, v in enumerate(organizaciones_aux)],ignore_index=True)
orgs = orgs.drop(orgs[orgs.organizacion=='.'].index)
orgs.head()

    id_accion                          organizacion
6           1                                   CAM
12          2                          AGRICULTORES
18          3  TRABAJADORES EMPRESA CONTRATISTA LGP
24          4                                 FEMAE
25          4                                FEUFRO

In [20]:
n_orgs = orgs[['organizacion']]
n_orgs = n_orgs.drop_duplicates()
n_orgs = n_orgs.reset_index(drop=True)
print(len(n_orgs))
organizaciones = n_orgs.reset_index(drop=True)
organizaciones['id_organizacion'] = organizaciones.index
organizaciones = organizaciones[['id_organizacion','organizacion']]
organizaciones = organizaciones.rename(columns={'organizacion':'nombre'})
print(n_orgs.head())
print(organizaciones.head())

#TABLA organizaciones en acción
d_orgs = n_orgs.to_dict()['organizacion']
d_orgs_i = dict((v,k) for (k,v) in d_orgs.items())
organizaciones_accion = orgs
organizaciones_accion.organizacion = organizaciones_accion.organizacion.replace(d_orgs_i)
organizaciones_accion = organizaciones_accion.reset_index(drop=True)
organizaciones_accion = organizaciones_accion.rename(columns={'organizacion':'id_organizacion'})
organizaciones_accion.head()

6143
                           organizacion
0                                   CAM
1                          AGRICULTORES
2  TRABAJADORES EMPRESA CONTRATISTA LGP
3                                 FEMAE
4                                FEUFRO
   id_organizacion                                nombre
0                0                                   CAM
1                1                          AGRICULTORES
2                2  TRABAJADORES EMPRESA CONTRATISTA LGP
3                3                                 FEMAE
4                4                                FEUFRO

   id_accion  id_organizacion
0          1                0
1          2                1
2          3                2
3          4                3
4          4                4

In [21]:
#TABLA tipos de elemento de demanda. Del anexo.
dict_tipo_ed = {'nombre':['Educacion','Pueblos originarios','Laborales','Ecologista, ambientalista','Feminista, mujeres','Salud','Cuestiones "valoricas"','Regionalistas, urbanas y/o locales','Minorías sexuales','Antiinmigrantes/grupos étnicos','Régimen militar','Vivienda','Sistema político','Otros']}
tipo_ed = pd.DataFrame(data=dict_tipo_ed)
tipo_ed['id'] = tipo_ed.index + 1
tipo_ed = tipo_ed[['id','nombre']]
tipo_ed = tipo_ed.append(pd.DataFrame(data = {'id':[99],'nombre':['Otros imprevistos']}))
tipo_ed = tipo_ed.reset_index(drop=True)
print(tipo_ed)

    id                              nombre
0    1                           Educacion
1    2                 Pueblos originarios
2    3                           Laborales
3    4           Ecologista, ambientalista
4    5                  Feminista, mujeres
5    6                               Salud
6    7              Cuestiones "valoricas"
7    8  Regionalistas, urbanas y/o locales
8    9                   Minorías sexuales
9   10      Antiinmigrantes/grupos étnicos
10  11                     Régimen militar
11  12                            Vivienda
12  13                    Sistema político
13  14                               Otros
14  99                   Otros imprevistos

In [22]:
#TABLAS elementos de demanda. Del anexo
dict_elementos_demanda = {'nombre':[
    'Educación en general',
    'Costos de educación, deudas educativas',
    'Cobertura, calidad y desigualdad educativa',
    'Educación gratuita, pública',
    'Beneficios asociados a condición de estudiante',
    'Faltas ético-legales. lucro en educación, irregularidades legales, coimas, etc.',
    'Aspectos curriculares y de contenidos',
    'Problemas vinculados a instituciones especificas',
    'Derechos o situación de profesores o funcionarios administrativos',
    'Otras demandas educativas',
    'Pueblos originarios en general',
    'Devolución de tierras',
    'Condiciones socioeconómicas, préstamos, programas de ayuda',
    'Condiciones legales, autonomía, representación política',
    'Represión policial, brutalidad policial',
    'Fallos de la justicia relativos a pueblos originarios',
    'Culturales (Amenazas a identidad y formas de vida, estigmas, discriminación)',
    'Otras demandas de pueblos originarios',
    'Laborales en general',
    'Salarios, indexación de salarios, reclamo de bonos o deudas',
    'Número y/o calidad de puestos de trabajo',
    'Condiciones de trabajo, horarios, accidentes o riesgos laborales',
    'Negociación colectiva, derechos colectivos de los trabajadores, mesas de diálogo',
    'Otras demandas laborales',
    'Pensiones, planes previsionales, sistema previsional',
    'Ecologista/ambientalista en general',
    'Construcción de centrales energéticas, puentes, represas, carreteras, etc.',
    'Desechos y residuos que contaminan o dañan el hábitat, la biodiversidad y/o la salud',
    'Tratamiento de residuos, reciclaje',
    'Polución sonora',
    'Capa de ozono, calentamiento global y demás cuestiones globales',
    'Otras demandas ambientalistas',
    'Feminista/mujeres en general',
    'Violencia contra mujeres',
    'Igualdad de salarios, cuotas políticas, educación o capacitación para mujeres, anti-discriminación',
    'Otras demandas feministas/de mujeres',
    'Salud en general',
    'Costos de salud',
    'Calidad y desigualdad en salud',
    'Salud gratuita, pública',
    'Irregularidades legales, coimas, etc.',
    'Cobertura de salud y enfermedades específicas',
    'Problemas vinculados a instituciones específicas',
    'Demandas vinculadas a médicos y otros funcionarios de la salud',
    'Nutrición, hábitos saludables',
    'Otras demandas de salud',
    'Cuestiones "valóricas". en general',
    'Aborto',
    'Divorcio',
    'Píldora del día después',
    'Eutanasia',
    'Otras demandas en cuestiones valóricas',
    'Regionalistas, locales en general',
    'Proyectos energéticos en la zona (protesta al estilo "Not in my backyard").',
    'Desarrollo local: mejor legislación, más fondos y condiciones generales para regiones o localidades',
    'Contaminación en la zona',
    'Cambios de uso de suelo (plan regulador); edificación en altura, edificación de grandes proyectos comerciales, edificaciones edilicias',
    'Infraestructura urbana; carreteras, aeropuertos, corredores de transporte y problemas de desplazamiento (Transantiago, por ejemplo).',
    'Otras demandas regionalistas o locales',
    'Minorías sexuales en general',
    'Derechos de gays',
    'Derechos de lesbianas',
    'Derechos de transexuales',
    'Otras demandas de minorías sexuales',
    'Antiinmigrantes/grupos étnicos en general',
    'Inmigrantes nacionales (migración dentro de Chile)',
    'Inmigrantes internacionales',
    'Otras demandas vinculadas a grupos étnicos o inmigrantes',
    'Régimen militar en general',
    'Personas, acontecimientos o símbolos ligados al régimen militar',
    'Investigación, esclarecimiento y/o procesamiento de militares ligados al régimen',
    'Acciones de grupos terroristas',
    'Otras demandas vinculadas a derechos humanos y régimen militar',
    'Conmemoraciones víctimas o fechas clave',
    'Vivienda en general',
    'Deudas habitacionales',
    'Construcción de viviendas',
    'Alto costo de la vivienda',
    'Campamentos, falta o precariedad de viviendas, reconstrucción post-desastre',
    'Otras demandas de vivienda',
    'Reforma del sistema político en general',
    'Cambio sistema binominal y otros cambios electorales',
    'Cambio constitucional',
    'Asamblea constituyente',
    'Leyes puntuales',
    'Solicitud de cambio en autoridad política',
    'Otras reformas en reglas políticas',
    'Corrupción',
    'Anti globalización, anti empresas transnacionales, anti neoliberalismo',
    'Derechos de los animales, vegetarianismo',
    'Derechos de consumidores',
    'Derechos de discapacitados y/o enfermos crónicos',
    'Derechos de los adultos mayores',
    'Derechos de grupos deportivos',
    'Derechos de grupos religiosos',
    'Pobreza y hambre',
    'Demanda por reforma de algún aspecto de la economía.',
    'Abusos y crímenes sexuales',
    'Demandas anarquistas, okupas y/o libertarias',
    'Eventos o situaciones internacionales',
    'Conmemoraciones',
    'Seguridad ciudadana'],
    'id':[100,101,102,103,104,105,106,107,108,109,200,201,202,203,204,205,206,207,300,301,302,303,304,305,306,
          400,401,402,403,404,405,406,500,501,502,503,600,601,602,603,604,605,606,607,608,609,700,701,702,703,
          704,705,800,801,802,803,804,805,806,900,901,902,903,904,1000,1001,1002,1003,1100,1101,1102,1103,1104,
          1105,1200,1201,1202,1203,1204,1205,1300,1301,1302,1303,1304,1305,1306,1307,1401,1402,1403,1404,1405,
          1406,1407,1408,1409,1410,1411,1412,1413,1414]}
elementos_demanda = pd.DataFrame(data=dict_elementos_demanda)
elementos_demanda['tipo'] = elementos_demanda.id//100
elementos_demanda = elementos_demanda[['id','nombre', 'tipo']]
elementos_demanda.head()

    id                                          nombre  tipo
0  100                            Educación en general     1
1  101          Costos de educación, deudas educativas     1
2  102      Cobertura, calidad y desigualdad educativa     1
3  103                     Educación gratuita, pública     1
4  104  Beneficios asociados a condición de estudiante     1

In [23]:
ed_texto = coes_o[['p19e1_texto','p19e2']]
#print(ed_texto[ed_texto.p19e1_texto!='.'])
ed_texto = ed_texto.drop(ed_texto[ed_texto.p19e1_texto=='.'].index)
#print(len(ed_texto))
ed_texto['id_accion'] = ed_texto.index
ed_texto = ed_texto.reset_index(drop=True)
print(len(ed_texto))
print(ed_texto.iloc[:20])

1775
                                p19e1_texto p19e2  id_accion
0   CONFORMACION FICHA DE PROTECCION SOCIAL     2         14
1   CONFORMACION FICHA DE PROTECCION SOCIAL     2         15
2                          PRECIO PRODUCTOS     2         21
3    RECHAZO A DECLARACIONES DE PEDRO SABAT     2         25
4                INSTALACION ALCANTARILLADO     2         30
5      LIBRE CIRCULACION NANAS POR COMPLEJO     2         38
6            MALA CALIDAD DE OBRAS PUBLICAS     2         43
7           CONTRA DECLARACIONES DE ALCALDE     2         45
8              APOYO A MOVIMIENTO POR AYSEN     2         73
9                 AUMENTO DE CUOTA DE PESCA     2         76
10             APOYO A MOVIMIENTO POR AYSEN     2         92
11         DISMINUCIÓN PRECIOS COMBISTIBLES     2        112
12         DISMINUCIÓN PRECIOS COMBISTIBLES     2        113
13         DISMINUCIÓN PRECIOS COMBISTIBLES     2        118
14         DISMINUCIÓN PRECIOS COMBISTIBLES     2        119
15         DISMINUCIÓN PRECIOS COMBISTIBLES     2        129
16                            APOYO A AYSEN     2        146
17     DECLARAR ZONA DE EMERGENCIA AGRICOLA     2        152
18                            APOYO A AYSEN     2        154
19                CONTRA VIOLENCIA POLICIAL     2        155

In [24]:
#elementos de demanda en texto
ed_extra = ed_texto[['p19e1_texto']]
ed_extra = ed_extra.drop_duplicates()
ed_extra = ed_extra.reset_index(drop=True)
ed_extra['id'] = ed_extra.index + 9900
ed_extra = ed_extra.rename(columns={'p19e1_texto':'nombre'})
ed_extra['tipo'] = 99
ed_extra = ed_extra[['id','nombre','tipo']]
print(len(ed_extra))
print(ed_extra.head())
elementos_demanda = elementos_demanda.append(ed_extra)
elementos_demanda = elementos_demanda.reset_index(drop=True)

955
     id                                   nombre  tipo
0  9900  CONFORMACION FICHA DE PROTECCION SOCIAL    99
1  9901                         PRECIO PRODUCTOS    99
2  9902   RECHAZO A DECLARACIONES DE PEDRO SABAT    99
3  9903               INSTALACION ALCANTARILLADO    99
4  9904     LIBRE CIRCULACION NANAS POR COMPLEJO    99

In [25]:
#ed extra en accion
ed_extra_accion = ed_texto[['id_accion','p19e1_texto','p19e2']]
ed_to_dict = ed_extra[['nombre']]
ed_to_dict.index = ed_extra.id
ed_extra_dict = ed_to_dict.to_dict()['nombre']
ed_extra_dict_i = dict((v,k) for (k,v) in ed_extra_dict.items())
ed_texto = ed_texto.replace(ed_extra_dict_i)
ed_texto = ed_texto.rename(columns={'p19e1_texto':'id_elemento_demanda','p19e2':'valencia_elemento_demanda'})
ed_texto = ed_texto[['id_accion','id_elemento_demanda','valencia_elemento_demanda']]
print(ed_texto.head())

   id_accion  id_elemento_demanda valencia_elemento_demanda
0         14                 9900                         2
1         15                 9900                         2
2         21                 9901                         2
3         25                 9902                         2
4         30                 9903                         2

In [26]:
#TABLA elementos de demanda en acción.
eda_aux = coes_o[['p19a1','p19b1','p19c1','p19d1','p19e1']].values.flatten()
eda_val_aux = coes_o[['p19a2','p19b2','p19c2','p19d2','p19e2']].values.flatten()
eda = pd.concat([pd.DataFrame([[i//5,v]],columns=['id_accion','id_elemento_demanda']) for i, v in enumerate(eda_aux)],ignore_index=True)
eda_val = pd.concat([pd.DataFrame([[i//5,v]],columns=['id_accion','valencia_elemento_demanda']) for i, v in enumerate(eda_val_aux)],ignore_index=True)
eda['valencia_elemento_demanda'] = eda_val.valencia_elemento_demanda
eda.head()

   id_accion id_elemento_demanda valencia_elemento_demanda
0          0
1          0
2          0
3          0
4          0

In [27]:
elementos_demanda_accion = eda.drop(eda[(eda.id_elemento_demanda==' ') & (eda.valencia_elemento_demanda==' ')].index)
elementos_demanda_accion = elementos_demanda_accion.drop(elementos_demanda_accion[elementos_demanda_accion.id_elemento_demanda=='9999'].index)
elementos_demanda_accion = elementos_demanda_accion.sort_values('id_accion')
elementos_demanda_accion = elementos_demanda_accion.append(ed_texto)
elementos_demanda_accion = elementos_demanda_accion.reset_index(drop=True)
elementos_demanda_accion.valencia_elemento_demanda = elementos_demanda_accion.valencia_elemento_demanda.replace({' ':'3'})
elementos_demanda_accion = elementos_demanda_accion.drop(elementos_demanda_accion[elementos_demanda_accion.id_elemento_demanda==' '].index)
#Hay códigos que no corresponden a ningún elemento de demanda, estos se eliminan
elementos_demanda_accion = elementos_demanda_accion.drop(elementos_demanda_accion[elementos_demanda_accion.id_elemento_demanda=='1314'].index)
elementos_demanda_accion = elementos_demanda_accion.reset_index(drop=True)
print(len(elementos_demanda_accion))
print(len(elementos_demanda_accion.drop(elementos_demanda_accion[elementos_demanda_accion.valencia_elemento_demanda==' '].index)))
print(elementos_demanda_accion.head())

19842
19640
   id_accion id_elemento_demanda valencia_elemento_demanda
0          1                 206                         2
1          1                1413                         1
2          2                 805                         2
3          3                 300                         2
4          4                 206                         2

In [28]:
#Tabla campos de conflictividad en accion
cc_aux = coes_o[['p20a','p20b']].values.flatten()
campos_conflictividad_accion = pd.concat([pd.DataFrame([[i//2,v]],columns=['id_accion','campo_conflictividad']) for i, v in enumerate(cc_aux)],ignore_index=True)
campos_conflictividad_accion = campos_conflictividad_accion.drop(campos_conflictividad_accion[campos_conflictividad_accion.campo_conflictividad=='.'].index)
campos_conflictividad_accion = campos_conflictividad_accion.reset_index(drop=True)

#Tabla campos de conflictividad
campos_conflictividad = campos_conflictividad_accion[['campo_conflictividad']]
campos_conflictividad = campos_conflictividad.drop(campos_conflictividad[campos_conflictividad.campo_conflictividad=='.'].index)
campos_conflictividad = campos_conflictividad.drop_duplicates()
campos_conflictividad = campos_conflictividad.reset_index(drop=True)
campos_conflictividad['id'] = campos_conflictividad.index
campos_conflictividad = campos_conflictividad[['id','campo_conflictividad']]
campos_conflictividad = campos_conflictividad.rename(columns={'campo_conflictividad':'nombre'})
dict_cc = campos_conflictividad.to_dict()['nombre']
dict_cc_i = dict((v,k) for k, v in dict_cc.items())
campos_conflictividad_accion.campo_conflictividad = campos_conflictividad_accion.campo_conflictividad.replace(dict_cc_i)
print(campos_conflictividad_accion.head(10))
print(campos_conflictividad)

   id_accion  campo_conflictividad
0          1                     0
1          2                     1
2          3                     2
3          4                     0
4          5                     2
5          5                     3
6          6                     0
7          7                     0
8          8                     4
9          9                     2
    id                                             nombre
0    0                    IDENTIDAD, MEMORIA Y PATRIMONIO
1    1                   PRESTACIÓN DE SERVICIOS PÚBLICOS
2    2                                   LABORAL/SALARIAL
3    3                          SITUACIÓN/MEDIDAS LEGALES
4    4                        VALORES/CREENCIAS/IDENTIDAD
5    5  RECURSOS NATURALES Y EXTERNALIDADES SOCIOAMBIE...
6    6                   OTROS CONFLICTOS SOCIOECONÓMICOS
7    7    CUESTIONAMIENTO Y/O RECONOCIMIENTO DE AUTORIDAD
8    8                             GESTIÓN ADMINISTRATIVA
9    9                                             TIERRA
10  10          USO DE SUELO, NORMATIVA E INFRAESTRUCTURA
11  11                        INCUMPLIMIENTO DE CONVENIOS
12  12                                               OTRO
13  13                   POLÍTICA Y AUTONOMÍA TERRITORIAL
14  14                RECURSOS NATURALES Y MEDIO AMBIENTE
15  15                                   DERECHOS HUMANOS
16  16                                SEGURIDAD CIUDADANA
17  17                                IDEOLÓGICO-POLÍTICO
18  18              ADMINISTRACIÓN DE RECURSOS ECONÓMICOS
19  19                                DESASTRES NATURALES
20  20                   LÍMITES POLÍTICO-ADMINISTRATIVOS
21  21                                    VECINAL/COMUNAL

In [29]:
#Tabla Actores
ados_aux = coes_o[['p15a','p15b']].values.flatten()
antes_aux = coes_o[['p18a','p18b']].values.flatten()
actores_aux = ados_aux.tolist() + antes_aux.tolist()
actores = pd.DataFrame(data=actores_aux,columns=['actores'])
actores = actores.drop_duplicates()
actores = actores.drop(actores[actores.actores=='.'].index)
actores = actores.reset_index(drop=True)
actores['id'] = actores.index
actores = actores[['id','actores']]
print(actores.head())
print(len(actores))
dict_actores = actores.to_dict()['actores']
dict_actores_i = dict((v,k) for k, v in dict_actores.items())

#Tabla actores demandados
actores_demandados = pd.concat([pd.DataFrame([[i//2,v]],columns=['id_accion','id_actor']) for i, v in enumerate(ados_aux)])
actores_demandados = actores_demandados.reset_index(drop=True)
actores_demandados = actores_demandados.drop(actores_demandados[actores_demandados.id_actor=='.'].index)
actores_demandados = actores_demandados.reset_index(drop=True)
actores_demandados.id_actor = actores_demandados.id_actor.replace(dict_actores_i)
print(actores_demandados.head())

#Tabla actores demandantes
actores_demandantes = pd.concat([pd.DataFrame([[i//2,v]],columns=['id_accion','id_actor']) for i, v in enumerate(antes_aux)])
actores_demandantes = actores_demandantes.reset_index(drop=True)
actores_demandantes = actores_demandantes.drop(actores_demandantes[actores_demandantes.id_actor=='.'].index)
actores_demandantes = actores_demandantes.reset_index(drop=True)
actores_demandantes.id_actor = actores_demandantes.id_actor.replace(dict_actores_i)
print(actores_demandantes.head())

   id                   actores
0   0            GOBIERNO LOCAL
1   1                   MINERÍA
2   2          GOBIERNO CENTRAL
3   3  ORGANIZACIONES POLÍTICAS
4   4         GOBIERNO REGIONAL
40
   id_accion  id_actor
0          2         0
1          3         1
2          4         2
3          5         0
4          8         3
   id_accion  id_actor
0          0        36
1          1        37
2          1        36
3          2        24
4          3         7

In [44]:
#Tabla Tipos de tacticas de protesta
tipos_tp_dict = {'nombre':['Pacíficas 1',
                           'Paíficas 2',
                           'Artísticas y cuasi-artísticas',
                           'Disruptivas no violentas',
                           'Autodestructivas',
                           'Violentas',
                           'Otras']}
tipos_tp = pd.DataFrame(data = tipos_tp_dict)
tipos_tp['id'] = tipos_tp.index
tipos_tp = tipos_tp[['id','nombre']]
tipos_tp

   id                         nombre
0   0                    Pacíficas 1
1   1                     Paíficas 2
2   2  Artísticas y cuasi-artísticas
3   3       Disruptivas no violentas
4   4               Autodestructivas
5   5                      Violentas
6   6                          Otras

In [31]:
#Tabla Tacticas de protesta
tp_otras = coes_o[['p29f_texto']]
tp_aux = coes_o[['p29a','p29b','p29c','p29d','p29e','p29f']].values.flatten()
tacticas_protesta_dict = {'nombre':['Marcha',
                               'Manifestación',
                               'Acto',
                               'Caravana',
                               'Recolección',
                               'Desobediencia',
                               'Conferencia',
                               'Asamblea',
                               'Rememoración',
                               'Coro',
                               'Boicot',
                               'Rezo',
                               'Vigilia',
                               'Festejo',
                               'Performance manifestantes',
                               'Performance artistas',
                               'Actividades simbólicas',
                               'Huelga',
                               'Toma de edificios',
                               'Ocupación de predio',
                               'Ocupación de espacio público',
                               'Corte de ruta',
                               'Interrupción de actividades de autoridades',
                               'Funa','Huelga de hambre',
                               'Acto autodestructivo',
                               'Incendio de vehículo',
                               'Destrucción propuedad pública',
                               'Saqueo de tiendas',
                               'Artefactos explosivos',
                               'Agresiones entre manifestantes',
                               'Enfrentamientos violentos contra manifestantes',
                               'Ataque a carabineros',
                               'Ataque a transeuntes',
                               'Toma de rehenes'],
                          'tipo':[0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,3,3,3,3,3,3,3,4,4,5,5,5,5,5,5,5,5,5]}
tacticas_protesta = pd.DataFrame(data= tacticas_protesta_dict)
print(tacticas_protesta.head())
tp_otras = tp_otras.drop(tp_otras[tp_otras.p29f_texto=='.'].index)
print(len(tp_otras))
tp_otras = tp_otras.drop_duplicates()
tp_otras = tp_otras.rename(columns={'p29f_texto':'nombre'})
tp_otras['tipo'] = 6
print(tp_otras.head())
tacticas_protesta = tacticas_protesta.append(tp_otras)
tacticas_protesta = tacticas_protesta.reset_index(drop=True)
tacticas_protesta['id'] = tacticas_protesta.index + 1
tacticas_protesta = tacticas_protesta[['id','nombre','tipo']]
print(tacticas_protesta)

          nombre  tipo
0         Marcha     0
1  Manifestación     0
2           Acto     0
3       Caravana     0
4    Recolección     0
6
                       nombre  tipo
4819   EVASIÓN PAGO DE PASAJE     6
10117            LINCHAMIENTO     6
    id                                          nombre  tipo
0    1                                          Marcha     0
1    2                                   Manifestación     0
2    3                                            Acto     0
3    4                                        Caravana     0
4    5                                     Recolección     0
5    6                                   Desobediencia     0
6    7                                     Conferencia     1
7    8                                        Asamblea     1
8    9                                    Rememoración     1
9   10                                            Coro     1
10  11                                          Boicot     1
11  12                                            Rezo     1
12  13                                         Vigilia     1
13  14                                         Festejo     1
14  15                       Performance manifestantes     2
15  16                            Performance artistas     2
16  17                          Actividades simbólicas     2
17  18                                          Huelga     3
18  19                               Toma de edificios     3
19  20                             Ocupación de predio     3
20  21                    Ocupación de espacio público     3
21  22                                   Corte de ruta     3
22  23      Interrupción de actividades de autoridades     3
23  24                                            Funa     3
24  25                                Huelga de hambre     4
25  26                            Acto autodestructivo     4
26  27                            Incendio de vehículo     5
27  28                   Destrucción propuedad pública     5
28  29                               Saqueo de tiendas     5
29  30                           Artefactos explosivos     5
30  31                  Agresiones entre manifestantes     5
31  32  Enfrentamientos violentos contra manifestantes     5
32  33                            Ataque a carabineros     5
33  34                            Ataque a transeuntes     5
34  35                                 Toma de rehenes     5
35  36                          EVASIÓN PAGO DE PASAJE     6
36  37                                    LINCHAMIENTO     6

In [32]:
#Tabla Tácticas en acción
tacticas_accion = pd.concat([pd.DataFrame([[i//6,v]],columns=['id_accion','id_tactica']) for i, v in enumerate(tp_aux)],ignore_index=True)
tp_otras.index = [36,37]
tp_otras_d = tp_otras.to_dict()['nombre']
tp_otras_r = dict((v,k) for k,v in tp_otras_d.items())
tp_accion_otras = coes_o[['p29f_texto']]
tp_accion_otras = tp_accion_otras.rename(columns={'p29f_texto':'id_tactica'})
tp_accion_otras = tp_accion_otras.drop(tp_accion_otras[tp_accion_otras.id_tactica=='.'].index)
print(tp_accion_otras)
tp_accion_otras['id_accion'] = tp_accion_otras.index
tp_accion_otras.id_tactica = tp_accion_otras.id_tactica.replace(tp_otras_r)
print(tp_accion_otras)
tp_accion_otras = tp_accion_otras[['id_accion','id_tactica']]
print(len(tp_accion_otras))
print(len(tacticas_accion))
tacticas_accion = tacticas_accion.append(tp_accion_otras)
tacticas_accion = tacticas_accion.sort_values('id_accion')
print(tacticas_accion[tacticas_accion.id_tactica==36])
print('size',len(tacticas_accion))
tacticas_accion = tacticas_accion.reset_index(drop=True)
tacticas_accion = tacticas_accion.drop(tacticas_accion[tacticas_accion.id_tactica==' '].index)
tacticas_accion = tacticas_accion.reset_index(drop=True)
print(tacticas_accion.head())
print('size',len(tacticas_accion))

                   id_tactica
4819   EVASIÓN PAGO DE PASAJE
4836   EVASIÓN PAGO DE PASAJE
4837   EVASIÓN PAGO DE PASAJE
4838   EVASIÓN PAGO DE PASAJE
10117            LINCHAMIENTO
10125            LINCHAMIENTO
       id_tactica  id_accion
4819           36       4819
4836           36       4836
4837           36       4837
4838           36       4838
10117          37      10117
10125          37      10125
6
69066
      id_accion id_tactica
4819       4819         36
4836       4836         36
4837       4837         36
4838       4838         36
size 69072
   id_accion id_tactica
0          0         30
1          1         30
2          1         27
3          2          2
4          3         18
size 18106

In [51]:
print(tacticas_accion[tacticas_accion.id_tactica==37])
print(tacticas_accion[tacticas_accion.id_tactica=='99'])
tacticas_accion = tacticas_accion.drop(tacticas_accion[tacticas_accion.id_tactica=='99'].index)

       id_accion id_tactica
15855      10117         37
15865      10125         37
       id_accion id_tactica
7704        4819         99
7730        4836         99
7732        4837         99
7736        4838         99
15854      10117         99
15867      10125         99

In [52]:
#Preview all final tables
print('acciones')
print(acciones.head())
print('medios')
print(medios.head())
print('tipo_medio')
print(tipo_medio.head())
print('tipo_grupo_social')
print(tipos_grupo_social.head())
print('grupos_sociales')
print(grupos_sociales.head())
print('grupos_accion')
print(grupos_accion.head())
print('organizaciones')
print(organizaciones.head())
print('organizacionesaccion')
print(organizaciones_accion.head())
print('tipo_ed')
print(tipo_ed.head())
print('elemenetos_demanda')
print(elementos_demanda.head())
print('elementos_demanda_accion')
print(elementos_demanda_accion.head())
print('campos_conflictividad')
print(campos_conflictividad.head())
print('campos_conflictividad_accion')
print(campos_conflictividad_accion.head())
print('actores')
print(actores.head())
print('actores_demandados')
print(actores_demandados.head())
print('actores_demandantes')
print(actores_demandantes.head())
print('tipos_tacticas_protesta')
print(tipos_tp.head())
print('tacticas_protesta')
print(tacticas_protesta.head())
print('tacticas_protesta_accion')
print(tacticas_accion.head())

acciones
  numero_pagina  tipo_noticia numero_lineas numero_respaldo repetida  comuna  \
0            C13            1            50               2             8203
1            C13            1            50               1        1    9101
2              6            1           120               1             4204
3              4            1            56               1             3202
4              7            1            90             171             9101

                                           localidad rural_urbana  \
0                                            PAICAVI            0
1                                             BOYECO            0
2                                       VALLE CHOAPA            0
3  INSTALACIONES DE TRANSPORTE Y CHANCADO DIVISIO...            0
4                              PLAZA TEODORO SCHMIDT            1

  lugar_objetivo id_episodio    ...     manifestantes_muertos  \
0                               ...
1                               ...
2                               ...
3                               ...
4                               ...

  manifestantes_muertos_estimado seguridad_muertos seguridad_muertos_estimado  \
0
1
2
3
4

  terceros_muertos terceros_muertos_estimado id_medio fecha_observacion  \
0                                                   0        2017-11-10
1                                                   1        2017-11-10
2                                                   2        2018-12-28
3                                                   3        2018-01-13
4                                                   4        2018-04-04

  fecha_inicio  fecha_fin
0   2012-01-01        NaT
1   2012-01-01        NaT
2   2012-01-02        NaT
3   2012-01-03        NaT
4   2012-01-03 2012-01-03

[5 rows x 47 columns]
medios
                         nombre  tipo
0                   EL MERCURIO     1
1                    COMBINADOS     3
2  DIARIO LA REGIÓN DE COQUIMBO     0
3             DIARIO DE ATACAMA     0
4                AUSTRAL TEMUCO     0
tipo_medio
   id                nombre
0   0  Circulación regional
1   1  Circulación nacional
2   2          Radio Biobío
3   3             Combinado
tipo_grupo_social
   id                        nombre
0   0                     Sexo/Edad
1   1                Grupos étnicos
2   2                   Estudiantes
3   3              Grupos laborales
4   4  Partidos, religión y deporte
grupos_sociales
   id                        nombre  tipo
0   1                       Hombres     0
1   2                       Mujeres     0
2   3                       Jóvenes     0
3   4               Adultos mayores     0
4   5  Pueblos originarios: mapuche     1
grupos_accion
   id_accion  id_grupo_social
0          0               30
1          1               30
2          1                5
3          2               26
4          3               13
organizaciones
   id_organizacion                                nombre
0                0                                   CAM
1                1                          AGRICULTORES
2                2  TRABAJADORES EMPRESA CONTRATISTA LGP
3                3                                 FEMAE
4                4                                FEUFRO
organizacionesaccion
   id_accion  id_organizacion
0          1                0
1          2                1
2          3                2
3          4                3
4          4                4
tipo_ed
   id                     nombre
0   1                  Educacion
1   2        Pueblos originarios
2   3                  Laborales
3   4  Ecologista, ambientalista
4   5         Feminista, mujeres
elemenetos_demanda
    id                                          nombre  tipo
0  100                            Educación en general     1
1  101          Costos de educación, deudas educativas     1
2  102      Cobertura, calidad y desigualdad educativa     1
3  103                     Educación gratuita, pública     1
4  104  Beneficios asociados a condición de estudiante     1
elementos_demanda_accion
   id_accion id_elemento_demanda valencia_elemento_demanda
0          1                 206                         2
1          1                1413                         1
2          2                 805                         2
3          3                 300                         2
4          4                 206                         2
campos_conflictividad
   id                            nombre
0   0   IDENTIDAD, MEMORIA Y PATRIMONIO
1   1  PRESTACIÓN DE SERVICIOS PÚBLICOS
2   2                  LABORAL/SALARIAL
3   3         SITUACIÓN/MEDIDAS LEGALES
4   4       VALORES/CREENCIAS/IDENTIDAD
campos_conflictividad_accion
   id_accion  campo_conflictividad
0          1                     0
1          2                     1
2          3                     2
3          4                     0
4          5                     2
actores
   id                   actores
0   0            GOBIERNO LOCAL
1   1                   MINERÍA
2   2          GOBIERNO CENTRAL
3   3  ORGANIZACIONES POLÍTICAS
4   4         GOBIERNO REGIONAL
actores_demandados
   id_accion  id_actor
0          2         0
1          3         1
2          4         2
3          5         0
4          8         3
actores_demandantes
   id_accion  id_actor
0          0        36
1          1        37
2          1        36
3          2        24
4          3         7
tipos_tacticas_protesta
   id                         nombre
0   0                    Pacíficas 1
1   1                     Paíficas 2
2   2  Artísticas y cuasi-artísticas
3   3       Disruptivas no violentas
4   4               Autodestructivas
tacticas_protesta
   id         nombre  tipo
0   1         Marcha     0
1   2  Manifestación     0
2   3           Acto     0
3   4       Caravana     0
4   5    Recolección     0
tacticas_protesta_accion
   id_accion id_tactica
0          0         30
1          1         30
2          1         27
3          2          2
4          3         18

In [53]:
#Write tables to csv
base = "COES/ForDB/"
acciones.to_csv(base+"acciones.csv")
medios.to_csv(base+"medios.csv")
tipo_medio.to_csv(base+"tipo_medio.csv",index=False)
tipos_grupo_social.to_csv(base+"tipos_grupo_social.csv",index=False)
grupos_sociales.to_csv(base+"grupos_sociales.csv",index=False)
grupos_accion.to_csv(base+"grupos_accion.csv",index=False)
organizaciones.to_csv(base+"organizaciones.csv",index=False)
organizaciones_accion.to_csv(base+"organizaciones_accion.csv",index=False)
tipo_ed.to_csv(base+"tipo_ed.csv",index=False)
elementos_demanda.to_csv(base+"elementos_demanda.csv",index=False)
elementos_demanda_accion.to_csv(base+"elementos_demanda_accion.csv",index=False)
campos_conflictividad.to_csv(base+"campos_conflictividad.csv",index=False)
campos_conflictividad_accion.to_csv(base+"campos_conflictividad_accion.csv",index=False)
actores.to_csv(base+"actores.csv",index=False)
actores_demandados.to_csv(base+"actores_demandados.csv",index=False)
actores_demandantes.to_csv(base+"actores_demandantes.csv",index=False)
tipos_tp.to_csv(base+"tipos_tp.csv",index=False)
tacticas_protesta.to_csv(base+"tacticas_protesta.csv",index=False)
tacticas_accion.to_csv(base+"tacticas_accion.csv",index=False)